### ISSUE TITLE
Building is broken (at least on macOS)

### ISSUE THREAD

**Issue by dei-layborer** [Ponup/thiefcatcher#8]
When trying to build on macOS (13.1 on Apple Silicon), I get an error that ``thiefcatcher/Core/conanbuildinfo.cmake`` cannot be found.  Searching the repo, the only reference to that file I can find is in the ``.gitignore``, so I don't know if that's the problem.

**Comment by santiagolizardo** [comment]
Hi @dei-layborer ; Thanks for reporting the issue. Your problem occurs when `conan install .` hasn't been ran on the Core directory.
I updated the README file with instructions for Linux/Macos but essentially before any cmake command run `pushd Core && conan install . && popd`
Hope that helps

**Comment by dei-layborer** [comment]
Thanks for the reply!  Unfortunately that hasn't fixed the build process, as I get an error with the command you added:

```
conanfile.txt: Installing package
Requirements
    fmt/7.1.3 from 'conancenter' - Downloaded
    rapidjson/cci.20211112 from 'conancenter' - Downloaded
Packages
    fmt/7.1.3:070f9bf1d15cf4b2a694de71f450816c2d2f2f25 - Missing
    rapidjson/cci.20211112:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Download

Installing (downloading, building) binaries...
ERROR: Missing binary: fmt/7.1.3:070f9bf1d15cf4b2a694de71f450816c2d2f2f25

fmt/7.1.3: WARN: Can't find a 'fmt/7.1.3' package for the specified settings, options and dependencies:
- Settings: arch=armv8, build_type=Release, compiler=apple-clang, compiler.libcxx=libc++, compiler.version=14, os=Macos
- Options: fPIC=True, header_only=False, shared=False, with_fmt_alias=False, with_os_api=True
- Dependencies:
- Requirements:
- Package ID: 070f9bf1d15cf4b2a694de71f450816c2d2f2f25

ERROR: Missing prebuilt package for 'fmt/7.1.3'
Use 'conan search fmt/7.1.3@ --table=table.html -r=remote' and open the table.html file to see available packages
Or try to build locally from sources with '--build=fmt'

More Info at 'https://docs.conan.io/en/latest/faq/troubleshooting.html#error-missing-prebuilt-package'
```

**Comment by santiagolizardo** [comment]
Closing as I am now using a newer version of `fmt`. The error could probably have been resolved doing `conan install . --build=fmt/7.1.3`. Only learned this recently, sorry! :)

**Comment by dei-layborer** [comment]
I appreciate the follow-up, but building is still broken (this time on Linux).  It's again because of ``fmt``, with the binary still missing.
